In [1]:
import numpy as np

In [2]:
arr1=np.array([[1,2,3,],
               [4,5,6]])

In [3]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr1[0,1]

2

In [5]:
#to sum row wise
arr1.sum(axis=1)

array([ 6, 15])

In [6]:
#to sum collum wise
arr1.sum(axis=0)

array([5, 7, 9])

In [7]:
b=np.array([[7,8,9],[2,8,0]])

In [ ]:
#to have t
a.dot(b)