In [1]:
import numpy as np
#numpy is faster than python and it takes lesss space to use a list

In [2]:
# initialization array in numpy
array1=np.array([[3,2,5,7,0],[1,12.3,3,4,5]], dtype="int32")
print(array1)
print(type(array1))

[[ 3  2  5  7  0]
 [ 1 12  3  4  5]]
<class 'numpy.ndarray'>


In [3]:
array1.shape
array1.dtype

dtype('int32')

In [4]:
# added  bank array of 4 size
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
#2d blank array
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
a=np.zeros(4)
a
b=np.ones(6).dtype

In [7]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [8]:
array1

array([[ 3,  2,  5,  7,  0],
       [ 1, 12,  3,  4,  5]])

In [9]:
# it is not matrix wise multipication
array1*array1

array([[  9,   4,  25,  49,   0],
       [  1, 144,   9,  16,  25]])

In [10]:
np.array([12**12])

array([8916100448256], dtype=int64)

## slicing

In [11]:
array1

array([[ 3,  2,  5,  7,  0],
       [ 1, 12,  3,  4,  5]])

In [12]:
array1[4:6]

array([], shape=(0, 5), dtype=int32)

In [13]:
array2=np.array([1,2,3,4,5,6])

In [14]:
array2[2:3]

array([3])

In [15]:
arr = array2[2:4]

In [16]:
arr[0]

3

In [17]:
arr[0]=199

In [18]:
arr

array([199,   4])

In [19]:
array2

array([  1,   2, 199,   4,   5,   6])

In [20]:
arr=array2[2:4].copy()

In [21]:
arr

array([199,   4])